"""New summative items for the Trailblazer Trek test bank.

These are NOT the in-module knowledge checks. Students who complete the modules
have already seen those questions with the answers revealed, which makes them
unsuitable on their own for summative assessment. The items below were written
separately for exams, target application and analysis rather than recall, and
are tagged to the ACGM learning outcome for GOVT 2306 they assess.

Tuple format: (chapter, outcome, level, stem, [options], correct_index, rationale)
level: "Application" | "Analysis" | "Comprehension"
"""

ITEMS = [
# ───────────────────────── Chapter 1 ─────────────────────────
(1,"8","Analysis",
 "A researcher finds that Texans consistently favor low taxes, limited regulation, and deference to established business leaders, while showing little interest in using government to reduce inequality. Using Elazar's typology, this pattern is best described as:",
 ["Moralistic","A blend of traditionalistic and individualistic","Purely moralistic with individualistic elements","Egalitarian"],1,
 "Elazar's traditionalistic culture emphasizes preserving the existing social order under established elites; individualistic culture treats government as a marketplace serving private and economic interests. Texas is generally classified as a blend of the two."),
(1,"8","Application",
 "A demographer notes that Texas has had no racial or ethnic majority since 2004 and that one group became the largest in roughly 2022. That largest group is:",
 ["Non-Hispanic white Texans","Black Texans","Hispanic Texans","Asian Texans"],2,
 "Texas lost its white majority in 2004 and by 2022 Hispanic Texans had become the largest single group, at roughly 40 percent, essentially even with non-Hispanic white Texans."),
(1,"1","Comprehension",
 "Which sequence correctly orders these events in Texas history?",
 ["Republic of Texas, Mexican independence, statehood, secession","Mexican independence, Republic of Texas, statehood, secession","Statehood, Mexican independence, Republic of Texas, secession","Secession, Republic of Texas, statehood, Mexican independence"],1,
 "Mexico won independence from Spain in 1821; Texas won independence from Mexico in 1836; Texas joined the United States in 1845; Texas seceded in 1861."),
(1,"8","Analysis",
 "The 1901 Spindletop gusher is treated as a turning point in Texas history primarily because it:",
 ["Ended Reconstruction in Texas","Transformed a largely rural agricultural economy into an industrial one","Established the Texas Railroad Commission","Caused Texas to secede from the Union"],1,
 "Spindletop launched the oil boom that industrialized the Texas economy, reshaping its population, politics, and public revenue."),
(1,"7","Application",
 "A student argues that Juneteenth deserves its status as a holiday because it marks a legal turning point rather than a cultural celebration alone. The strongest support for that argument is that June 19, 1865 marks when:",
 ["The Texas Constitution was ratified","Union troops reached Galveston and enforced emancipation in Texas","The Civil War formally ended nationwide","Texas was readmitted to the Union"],1,
 "Juneteenth commemorates the arrival of Union troops in Galveston enforcing the emancipation of enslaved Texans."),

# ───────────────────────── Chapter 2 ─────────────────────────
(2,"1","Analysis",
 "Texas's 1876 constitution created a weak governor, a part-time legislature, and elected judges. The best explanation for this cluster of choices is that the framers were reacting against:",
 ["Federal overreach during the Mexican-American War","The centralized Reconstruction government of Governor E. J. Davis","The failures of the Republic of Texas","Excessive power held by county governments"],1,
 "The 1876 framers deliberately fragmented and weakened state government in reaction to the Davis administration's centralized Reconstruction-era power."),
(2,"1","Application",
 "A legislator wants to amend the Texas Constitution. Which sequence is required?",
 ["A two-thirds vote of each chamber, then approval by a majority of voters","A majority vote of each chamber, then the governor's signature","A two-thirds vote of each chamber, then the governor's signature","Approval by voters, then ratification by the Legislature"],0,
 "Texas constitutional amendments require a two-thirds vote of all members elected to each chamber and then approval by a majority of voters. The governor plays no formal role."),
(2,"3","Analysis",
 "Article II of the Texas Constitution forbids a person attached to one department of government from exercising power belonging to another, yet the lieutenant governor presides over the Senate. This is best characterized as:",
 ["A violation that courts have struck down","An express exception within the constitutional design that blurs the separation in practice","Evidence that Texas has no separation of powers","A federal requirement imposed on Texas"],1,
 "Article II permits exceptions expressly made in the constitution. The lieutenant governor, elected as an executive officer but presiding over the Senate, is a notable case where the branches overlap by design."),
(2,"3","Comprehension",
 "Which pairing correctly matches a Texas branch with a check it holds over another branch?",
 ["Judiciary: calling special sessions","Legislature: overriding a veto by two-thirds of each chamber","Governor: impeaching state officials","Judiciary: confirming gubernatorial appointments"],1,
 "The Legislature can override a gubernatorial veto by a two-thirds vote in each chamber. Special sessions are called by the governor, impeachment begins in the House, and confirmation is a Senate power."),
(2,"1","Analysis",
 "Critics call the Texas Constitution excessively long and frequently amended. Supporters of the design would most likely respond that its length and amendment rate:",
 ["Prove the document is poorly written","Reflect deliberate limits on government that require voter approval to change","Show that Texas courts refuse to interpret it","Result from federal requirements"],1,
 "Because the 1876 document restricts government in detail rather than granting broad authority, changes usually require amendment, which requires a popular vote. Defenders view this as keeping power with the people."),

# ───────────────────────── Chapter 3 ─────────────────────────
(3,"2","Application",
 "A state law conflicts with a valid federal statute enacted within Congress's constitutional powers. Under the supremacy clause, the result is that:",
 ["The state law prevails because states are closer to the people","The federal law prevails","A federal court must first ask the state to repeal its law","The two laws operate simultaneously"],1,
 "The supremacy clause makes valid federal law supreme over conflicting state law, provided the federal law is within the powers the Constitution grants."),
(3,"2","Analysis",
 "Texas charges higher tuition to out-of-state students at its public universities. This is permissible under the privileges and immunities clause because:",
 ["The clause applies only to criminal matters","States may treat residents and nonresidents differently in limited ways such as residency-based benefits","The clause was repealed by the Fourteenth Amendment","Education is exclusively a federal responsibility"],1,
 "The clause bars discrimination against out-of-state citizens in fundamental matters, but states retain latitude for limited distinctions such as tuition and residency requirements."),
(3,"2","Comprehension",
 "Which best describes the significance of McCulloch v. Maryland (1819)?",
 ["It established that states may tax federal institutions","It established implied powers under the necessary and proper clause and affirmed national supremacy","It limited the commerce clause to the buying and selling of goods","It gave states the right to secede"],1,
 "McCulloch upheld the national bank under the necessary and proper clause, establishing implied powers, and held that a state may not tax a federal institution."),
(3,"2","Analysis",
 "A policy analyst describes a federal program in which Washington provides money for a broad purpose and lets each state design its own program with few restrictions. This best describes:",
 ["A categorical grant under cooperative federalism","A block grant, associated with new federalism","An unfunded mandate","Dual federalism"],1,
 "Block grants provide funds for a broad purpose with few strings, giving states flexibility. They are the signature tool of new federalism."),
(3,"3","Analysis",
 "Which statement most accurately distinguishes federalism from separation of powers?",
 ["Federalism divides power among branches; separation of powers divides it among levels","Federalism divides power among levels of government; separation of powers divides it among branches at the same level","They are two terms for the same concept","Federalism applies only to Texas; separation of powers applies only to the federal government"],1,
 "Federalism divides authority between national and state (and local) levels. Separation of powers divides authority among legislative, executive, and judicial branches within a level."),

# ───────────────────────── Chapter 4 ─────────────────────────
(4,"4","Application",
 "A bill passes the Texas House and Senate in different forms late in the session. The next procedural step is most likely:",
 ["The governor chooses which version to sign","A conference committee works out the differences","The bill dies automatically","The Texas Supreme Court resolves the conflict"],1,
 "When the chambers pass different versions, a conference committee of members from both chambers negotiates a single version for final approval."),
(4,"4","Analysis",
 "An observer claims the lieutenant governor is more powerful than the governor of Texas. The strongest evidence for this claim is that the lieutenant governor:",
 ["Can veto legislation","Controls Senate committee assignments and the flow of legislation","Appoints all state agency heads","Serves as chief justice of the Texas Supreme Court"],1,
 "As presiding officer of the Senate, the lieutenant governor controls committee assignments, referral, and the calendar, giving that office extensive influence over what becomes law."),
(4,"4","Comprehension",
 "Texas legislators are paid $7,200 per year plus a per diem while in session. The most commonly cited consequence of this compensation structure is that it:",
 ["Guarantees a legislature that mirrors the state's demographics","Favors candidates with independent wealth, flexible professions, or outside income","Requires legislators to meet year-round","Is set annually by the Legislative Budget Board"],1,
 "Low pay tends to restrict who can realistically serve, favoring those with independent means or flexible careers, a common critique of the citizen-legislature model."),
(4,"4","Application",
 "The governor wants the Legislature to address a single urgent issue in August of an odd-numbered year, after the regular session has ended. The governor may:",
 ["Extend the regular session by 30 days","Call a special session limited to 30 days and set its agenda","Order the Legislature to convene for 140 days","Pass the measure by executive order"],1,
 "Only the governor can call a special session; it may last up to 30 days, and the governor sets the subjects the Legislature may consider."),
(4,"6","Analysis",
 "In redistricting, 'cracking' refers to:",
 ["Concentrating a group's voters into as few districts as possible","Dividing a group's voters among many districts so they cannot form a majority in any","Drawing districts of unequal population","Redrawing districts more than once per decade"],1,
 "Cracking splits a group across districts to dilute its voting strength; packing concentrates the group into few districts to limit its influence elsewhere."),

# ───────────────────────── Chapter 5 ─────────────────────────
(5,"4","Analysis",
 "The Texas governor's line-item veto applies to:",
 ["Any bill passed by the Legislature","Individual spending items within appropriations bills","Constitutional amendments","Judicial decisions"],1,
 "The line-item veto allows the governor to strike individual spending items from appropriations bills without vetoing the entire measure. It does not apply to non-spending legislation."),
(5,"4","Application",
 "A newly elected Texas governor wants to change the direction of a major state agency governed by a six-year staggered-term board. The governor's most realistic path is to:",
 ["Fire the current board members immediately","Appoint replacements gradually as terms expire, subject to Senate confirmation","Issue an executive order dissolving the board","Ask the attorney general to remove the board"],1,
 "Staggered terms and narrow removal power mean a governor reshapes boards gradually through appointments, which generally require two-thirds Senate confirmation."),
(5,"4","Comprehension",
 "Which official is NOT independently elected as part of the Texas plural executive?",
 ["Attorney General","Comptroller of Public Accounts","Secretary of State","Commissioner of Agriculture"],2,
 "The Secretary of State is appointed by the governor. The attorney general, comptroller, land commissioner, and agriculture commissioner are elected statewide."),
(5,"3","Analysis",
 "A governor wishes to grant a pardon to a person convicted of a felony. Under the Texas Constitution, the governor generally may do so only:",
 ["With the approval of the Texas Supreme Court","On the written recommendation of the Board of Pardons and Paroles","After a two-thirds vote of the Senate","With the consent of the county that prosecuted the case"],1,
 "The governor's clemency power is constrained: a pardon or commutation generally requires a written recommendation from a majority of the Board of Pardons and Paroles. The governor may independently grant only a single 30-day reprieve."),
(5,"4","Analysis",
 "Despite constitutionally weak formal powers, Texas governors often exert substantial influence. The best explanation is their use of:",
 ["Judicial review","Informal powers such as persuasion, party leadership, media attention, and appointments accumulated over time","The power to dissolve the Legislature","Direct control over local governments"],1,
 "Because formal authority is limited, effective Texas governors rely heavily on informal powers and on the long-run effect of thousands of appointments."),

# ───────────────────────── Chapter 6 ─────────────────────────
(6,"4","Application",
 "A defendant convicted of a felony in a Texas district court exhausts intermediate appeals and seeks review by the state's highest court for criminal matters. That court is:",
 ["The Texas Supreme Court","The Court of Criminal Appeals","The Fifteenth Court of Appeals","A federal district court"],1,
 "Texas has two courts of last resort: the Texas Supreme Court for civil cases and the Court of Criminal Appeals for criminal cases."),
(6,"4","Analysis",
 "The most frequently cited criticism of electing Texas judges in partisan elections is that it:",
 ["Makes judges unaccountable to the public","Ties judges to campaign contributions and party sweeps, threatening the appearance of impartiality","Prevents voters from removing judges","Violates the U.S. Constitution"],1,
 "Critics argue partisan judicial elections create dependence on campaign money and allow straight-ticket sweeps to decide judgeships, undermining perceived impartiality. Supporters counter that elections provide direct accountability."),
(6,"4","Comprehension",
 "An appellate court that sends a case back to the trial court for further proceedings has:",
 ["Affirmed the decision","Reversed the decision","Remanded the case","Recused itself"],2,
 "To remand is to return a case to a lower court for further action. Affirming upholds the decision; reversing overturns it."),
(6,"4","Application",
 "A civil dispute involving a Texas state agency arises in 2026. Which court was created specifically to hear such cases statewide?",
 ["The Court of Criminal Appeals","The Fifteenth Court of Appeals","A justice of the peace court","The Sunset Advisory Commission"],1,
 "The Fifteenth Court of Appeals, operating since September 2024, has statewide jurisdiction over certain civil matters involving the state and its agencies."),
(6,"4","Analysis",
 "Under the Missouri Plan, judges are:",
 ["Elected in partisan elections","Appointed on the recommendation of a nominating commission and later face retention elections","Selected by the legislature alone","Appointed for life with no voter involvement"],1,
 "The Missouri Plan combines merit-based appointment through a nominating commission with subsequent retention elections in which voters decide whether a judge remains."),

# ───────────────────────── Chapter 7 ─────────────────────────
(7,"2","Application",
 "A Texas city of 30,000 residents adopts its own charter. It may then:",
 ["Exercise only powers the Legislature has specifically granted","Take any action not prohibited by state law or the constitution","Ignore state preemption laws","Levy a state income tax"],1,
 "Cities over 5,000 may adopt home-rule charters, allowing them to act unless prohibited by state law. General-law cities may exercise only powers expressly granted."),
(7,"2","Analysis",
 "The Legislature passes a law prohibiting cities from regulating a particular business practice, overriding several local ordinances. This is an example of:",
 ["Federalism","Preemption","Annexation","Home rule"],1,
 "Preemption occurs when state law limits or overrides local authority. It has become a recurring flashpoint as urban policy diverges from the Legislature."),
(7,"2","Comprehension",
 "Texas counties are described as having a 'plural executive' structure because:",
 ["The county judge holds all executive authority","Multiple county officials, such as the sheriff, clerk, and tax assessor-collector, are independently elected","Counties are governed by appointed managers","Counties have no executive officials"],1,
 "County government mirrors the state's fragmentation, with many independently elected officials rather than a single executive."),
(7,"2","Analysis",
 "Which statement best explains why special-purpose districts matter despite receiving little public attention?",
 ["They are the only governments allowed to levy property taxes","They outnumber cities and counties and deliver essential services such as schools, water, and hospitals","They are branches of the federal government","They exist only in rural areas"],1,
 "Texas has thousands of special districts delivering critical services, yet their elections and board meetings draw minimal attention, which raises accountability concerns."),
(7,"2","Application",
 "A city council adopts an ordinance under a council-manager form of government. Day-to-day implementation is the responsibility of:",
 ["The mayor acting alone","The professional city manager hired by the council","The county commissioners court","The governor's office"],1,
 "In the council-manager form, the elected council sets policy and a hired professional manager administers daily operations."),

# ───────────────────────── Chapter 8 ─────────────────────────
(8,"6","Application",
 "A Texan moves to a new county 20 days before an election and wants to vote there. Under Texas law, this voter:",
 ["May register at the polls on Election Day","Missed the registration deadline, which is 30 days before the election","May vote without registering","Must obtain a court order"],1,
 "Texas requires registration at least 30 days before an election and does not permit same-day registration."),
(8,"6","Analysis",
 "The Supreme Court's decision in Shelby County v. Holder (2013) affected Texas elections chiefly by:",
 ["Striking down the photo-ID requirement","Ending the coverage formula that had required federal preclearance of Texas election-law changes","Requiring Texas to adopt same-day registration","Abolishing the poll tax"],1,
 "Shelby County invalidated the coverage formula, ending mandatory federal preclearance for covered jurisdictions including Texas."),
(8,"5","Analysis",
 "A voter chooses a candidate mainly because the economy has performed well under the incumbent party. This is best described as:",
 ["Prospective voting","Retrospective voting","Pocketbook voting","Straight-ticket voting"],1,
 "Retrospective voting evaluates past performance. Prospective voting looks to future promises; pocketbook voting focuses on one's own financial situation."),
(8,"7","Comprehension",
 "The 1902 Texas poll tax and the white primary were significant because they:",
 ["Increased turnout among all Texans","Suppressed voting by Black, Latino, and poor Texans within a one-party system","Were required by the federal government","Applied only to municipal elections"],1,
 "Both devices restricted meaningful participation, particularly for Black, Mexican American, and poor voters, in an era when the Democratic primary decided elections."),
(8,"6","Analysis",
 "Texas turnout is persistently low relative to other states. Which combination of factors is most commonly cited?",
 ["A small population and few elections","A young population, weak political efficacy, and comparatively restrictive election procedures","Mandatory voting laws and high registration rates","Federal limits on state elections"],1,
 "Analysts commonly point to demographics, low political efficacy, and procedural friction as contributors to Texas's low turnout."),

# ───────────────────────── Chapter 9 ─────────────────────────
(9,"6","Application",
 "No candidate receives a majority in a Texas party primary. What happens next?",
 ["The candidate with the most votes is nominated","A runoff is held between the top two finishers","The party chair selects the nominee","The office remains vacant"],1,
 "Texas requires a majority to win a primary; when no candidate reaches it, a runoff between the top two decides the nomination."),
(9,"6","Analysis",
 "In Texas's open primary system, a registered voter may:",
 ["Vote in both parties' primaries in the same election","Vote in one party's primary without having registered with that party","Vote only in the primary of the party they registered with","Vote only if they attended a precinct convention"],1,
 "Texas uses an open primary: voters need not register by party but may participate in only one party's primary per election cycle."),
(9,"6","Comprehension",
 "Following the 2020 census, Texas casts how many electoral votes?",
 ["38","40","36","42"],1,
 "Texas gained two congressional seats after the 2020 census, giving it 38 House seats plus two senators, for 40 electoral votes."),
(9,"5","Analysis",
 "The 1960 Kennedy-Nixon debate is frequently cited in political science because it demonstrated that:",
 ["Radio audiences are more persuadable than television audiences","Visual presentation can shape perceptions of who won independent of the arguments made","Debates have no measurable effect on voters","Televised debates are legally required"],1,
 "Television viewers tended to judge Kennedy the winner while radio listeners were more evenly split, illustrating the power of visual presentation."),
(9,"5","Analysis",
 "After Citizens United v. FEC (2010), Super PACs may:",
 ["Contribute unlimited sums directly to candidate campaigns","Raise and spend unlimited sums independently, without coordinating with candidates","Accept money only from individuals","Operate only in federal elections"],1,
 "Super PACs may raise and spend unlimited amounts on independent expenditures but may not contribute to or coordinate with candidate campaigns."),

# ───────────────────────── Chapter 10 ─────────────────────────
(10,"5","Analysis",
 "The Shivercrat movement of the 1950s is historically significant because it:",
 ["Created the Texas Republican Party","Signaled the beginning of conservative Texas Democrats shifting toward the Republican Party","Established the white primary","Ended the poll tax"],1,
 "Governor Allan Shivers led conservative Texas Democrats to back Republican Eisenhower, an early sign of the realignment that eventually made Texas a Republican state."),
(10,"5","Application",
 "A Texan wants to influence their party's platform. The entry point in the party's temporary organization is the:",
 ["State convention","Precinct convention","Legislative Budget Board","Sunset Advisory Commission"],1,
 "Participation begins at the precinct convention, which selects delegates to the county or district convention, which in turn sends delegates to the state convention."),
(10,"5","Analysis",
 "Madison argued in Federalist No. 10 that factions should be:",
 ["Suppressed by law","Allowed to flourish and compete so that none dominates","Limited to two per state","Replaced by direct democracy"],1,
 "Madison held that eliminating factions would require destroying liberty, so the remedy is to let many factions compete and check one another."),
(10,"5","Comprehension",
 "Partisan polarization refers to:",
 ["The number of parties competing in an election","The widening ideological gap between the parties as moderates decline","The geographic distribution of party voters","The use of straight-ticket voting"],1,
 "Polarization describes parties moving further apart ideologically, with fewer moderates and reduced willingness to compromise."),
(10,"5","Analysis",
 "Recent Republican gains among Hispanic voters in South Texas most directly complicate which assumption?",
 ["That turnout is rising statewide","That demographic change automatically produces partisan change","That third parties influence Texas elections","That primaries determine general-election outcomes"],1,
 "The assumption that a growing Hispanic population would necessarily shift Texas toward Democrats is complicated by Republican gains among those same voters."),

# ───────────────────────── Chapter 11 ─────────────────────────
(11,"5","Application",
 "A professional association offers members discounted insurance and continuing-education courses. In interest-group theory, these are:",
 ["Purposive benefits","Solidary benefits","Material benefits","Collective goods"],2,
 "Material benefits are tangible rewards used to attract members and to counter the free rider problem."),
(11,"5","Analysis",
 "The free rider problem makes organizing difficult because individuals:",
 ["Cannot legally join interest groups","Can enjoy benefits a group wins without joining or paying","Are required to join multiple groups","Always prefer collective action"],1,
 "Because a group's policy victories typically benefit everyone in a category, individuals have an incentive to benefit without bearing the costs of membership."),
(11,"5","Analysis",
 "Interest-group PACs frequently follow the 'friendly incumbent rule,' meaning they:",
 ["Support challengers who share their views","Support sitting legislators to preserve access and avoid retaliation","Contribute equally to both parties","Refuse to make contributions"],1,
 "Because incumbents usually win and a spurned incumbent may retaliate, groups often back sitting legislators to maintain access."),
(11,"5","Application",
 "A group organizes thousands of ordinary citizens to email legislators about a bill. This tactic is:",
 ["Grasstops lobbying","Grassroots lobbying","Electioneering","Regulatory capture"],1,
 "Grassroots lobbying mobilizes large numbers of ordinary constituents; grasstops lobbying mobilizes a few especially influential individuals."),
(11,"7","Comprehension",
 "In Texas, lobbyists who exceed statutory thresholds must register with and report to:",
 ["The Sunset Advisory Commission","The Texas Ethics Commission","The Legislative Budget Board","The Secretary of State's elections division"],1,
 "The Texas Ethics Commission administers lobby registration, activity reports, and gift rules."),

# ───────────────────────── Chapter 12 ─────────────────────────
(12,"8","Analysis",
 "A policy provides benefits to a specific group while spreading its costs across all taxpayers. Using Lowi's typology, this is:",
 ["Regulatory policy","Redistributive policy","Distributive policy","Constituent policy"],2,
 "Distributive policy concentrates benefits on a particular group while dispersing costs broadly, as with many subsidies."),
(12,"8","Application",
 "Clean air is difficult for private markets to provide because it is:",
 ["Excludable and rivalrous","Non-excludable and non-rivalrous","Owned by individual landowners","Regulated only by local government"],1,
 "Public goods are non-excludable (you cannot readily prevent anyone from benefiting) and non-rivalrous (one person's use does not diminish another's), so markets tend to underprovide them."),
(12,"8","Comprehension",
 "Texas Senate Bill 2 (2025) is significant in education policy because it:",
 ["Eliminated the basic allotment","Created the state's first Education Savings Account program","Abolished charter schools","Required year-round schooling"],1,
 "SB 2 established Texas's first ESA (voucher-style) program, allowing families to use public funds toward private schooling."),
(12,"8","Analysis",
 "Texas declined to expand Medicaid under the Affordable Care Act. The most commonly cited consequence is:",
 ["A statewide surplus of insured adults","A coverage gap for adults earning too much for traditional Medicaid but too little for marketplace subsidies","The loss of all federal health funding","Mandatory enrollment in CHIP"],1,
 "In non-expansion states, adults in that income range often qualify for neither traditional Medicaid nor subsidized marketplace coverage."),
(12,"8","Application",
 "The 2021 Texas law generally permitting adults 21 and older to carry a handgun in public without a license is known as:",
 ["Campus carry","Permitless or constitutional carry","Open carry licensing","The castle doctrine"],1,
 "House Bill 1927 (2021) established permitless carry, sometimes called constitutional carry, for most adults not otherwise barred from possessing a firearm."),

# ───────────────────────── Chapter 13 ─────────────────────────
(13,"7","Application",
 "A defendant cannot afford an attorney in a Texas felony case. The right to appointed counsel derives from:",
 ["Miranda v. Arizona","Gideon v. Wainwright","Plyler v. Doe","Shelby County v. Holder"],1,
 "Gideon v. Wainwright (1963) established that states must provide counsel to criminal defendants who cannot afford an attorney."),
(13,"7","Analysis",
 "The most frequently raised structural criticism of indigent defense in Texas is that:",
 ["Public defenders are barred by state law","Judges, who are evaluated partly on docket efficiency, often control appointments and compensation of defense counsel","Defendants must pay the full cost of counsel","Only federal courts appoint attorneys"],1,
 "Because judges commonly appoint and set pay for defense counsel while also managing case flow, critics identify an inherent conflict of interest."),
(13,"7","Comprehension",
 "The Fifth Amendment protection against double jeopardy prevents:",
 ["Being questioned without an attorney","Being tried twice for the same offense by the same sovereign after acquittal","Excessive bail","Cruel and unusual punishment"],1,
 "Double jeopardy bars a second prosecution for the same offense by the same level of government after an acquittal."),
(13,"7","Analysis",
 "Texas voters approved Proposition 3 in 2025, which addressed:",
 ["The death penalty","Denial of bail for certain serious violent offenses","Indigent defense funding","Jury size in felony cases"],1,
 "Proposition 3 amended the constitution to require judges to deny bail to defendants accused of certain serious violent felonies."),
(13,"8","Analysis",
 "Texas leads the nation in both executions and exonerations. The most defensible inference from this pairing is that:",
 ["Texas courts are uniquely lenient","The scale of the system makes both outcomes more visible and keeps the risk of error central to policy debate","Exonerations prove executions are always accurate","The two statistics are unrelated"],1,
 "The combination is frequently cited in debate precisely because it juxtaposes the irreversibility of executions with documented wrongful convictions."),

# ───────────────────────── Chapter 14 ─────────────────────────
(14,"8","Application",
 "Texas has no personal income tax. Its single largest source of state tax revenue is the:",
 ["Franchise tax","Sales tax","Severance tax","Property tax"],1,
 "The state sales tax (6.25 percent, up to 8.25 percent with local add-ons) is the largest state tax revenue source. Property taxes are levied locally, not by the state."),
(14,"4","Analysis",
 "Before the Texas budget can take effect, the Comptroller must certify that it does not exceed anticipated revenue. This requirement is known as:",
 ["The line-item veto","Pay-as-you-go","Securitization","The biennial revenue estimate"],1,
 "Texas's constitutional pay-as-you-go rule requires a balanced budget certified by the Comptroller against the biennial revenue estimate."),
(14,"8","Comprehension",
 "The Economic Stabilization Fund, or Rainy Day Fund, is filled primarily by:",
 ["Sales tax collections","Oil and gas severance taxes","Federal grants","Lottery proceeds"],1,
 "The fund is filled largely by severance taxes on oil and natural gas production above a statutory threshold."),
(14,"8","Analysis",
 "Critics describe the Texas tax structure as regressive primarily because:",
 ["It relies on a graduated income tax","Sales and property taxes consume a larger share of income from lower earners","It exempts all businesses from taxation","Severance taxes are paid by consumers directly"],1,
 "Without an income tax, Texas depends on sales and property taxes, which generally take a larger proportional share from lower-income households."),
(14,"4","Application",
 "A state agency seeking funding for the next biennium begins the process by submitting:",
 ["A biennial revenue estimate","A legislative appropriations request","A Sunset self-evaluation report","A line-item veto message"],1,
 "Agencies submit legislative appropriations requests, which the Legislative Budget Board uses to draft the budget within the Comptroller's revenue estimate."),

# ───────────────────────── Chapter 15 ─────────────────────────
(15,"5","Analysis",
 "A polling firm surveys 800 respondents drawn to mirror the state's demographics; a competitor surveys 5,000 respondents recruited from its own website visitors. The first poll is likely more accurate because:",
 ["Smaller samples are always better","Representativeness matters more than raw sample size","Online respondents cannot be surveyed","It has a larger margin of error"],1,
 "Accuracy depends primarily on whether the sample represents the population. A large but self-selected sample can be badly biased."),
(15,"5","Application",
 "A campaign calls voters and asks, 'Would you still support Candidate X if you knew she raised your taxes?' This tactic is:",
 ["An exit poll","A push poll","A representative sample","Retrospective voting"],1,
 "Push polls are campaign messaging disguised as surveys, designed to change opinions rather than measure them."),
(15,"5","Comprehension",
 "The media's power to determine which issues receive public attention is called:",
 ["Framing","Priming","Agenda setting","Socialization"],2,
 "Agenda setting is the power to influence which topics the public considers important. Framing shapes how a story is understood; priming predisposes audiences toward particular judgments."),
(15,"5","Analysis",
 "The Bradley effect describes a gap between:",
 ["Exit polls and official returns in rural counties","What respondents tell live interviewers and how they actually vote","Two different polling firms' methodologies","Registered voters and likely voters"],1,
 "The Bradley effect refers to respondents giving socially acceptable answers to live interviewers that diverge from their actual votes, detectable by comparing live and automated polling."),
(15,"5","Analysis",
 "Describing the press as the 'fourth estate' emphasizes its role as:",
 ["A branch of government","A watchdog operating alongside the three branches","A partisan organization","A regulated public utility"],1,
 "The term casts the press as an additional check on government power, monitoring the legislative, executive, and judicial branches."),

# ───────────────────────── Chapter 16 ─────────────────────────
(16,"7","Analysis",
 "A Texan claims a city denied her a permit because of her ethnicity. This is best analyzed as:",
 ["A civil liberties claim, because government exceeded its power","A civil rights claim, because government treated her unequally","A federalism claim","A separation of powers claim"],1,
 "Civil rights claims concern unequal treatment by government; civil liberties claims concern government exceeding its authority over individuals."),
(16,"7","Application",
 "A Texas law classifies people by race. A reviewing court will apply:",
 ["Rational-basis review","Intermediate scrutiny","Strict scrutiny, requiring a compelling interest and narrow tailoring","No review at all"],2,
 "Racial classifications trigger strict scrutiny, the most demanding standard, which few such classifications survive."),
(16,"7","Analysis",
 "Hernandez v. Texas (1954) is a landmark because it held that:",
 ["Segregated public schools are unconstitutional","The Equal Protection Clause protects Mexican Americans as a class, extending beyond a Black-white framework","The white primary was unconstitutional","Flag burning is protected expression"],1,
 "Decided two weeks before Brown, Hernandez established that any group treated as 'a class apart' receives equal protection, extending the doctrine beyond race as narrowly conceived."),
(16,"1","Comprehension",
 "Texas's 1972 Equal Rights Amendment (Article I, Section 3a) is notable because it:",
 ["Duplicates the federal Equal Rights Amendment exactly","Was adopted by Texas voters although the federal ERA was never ratified, and covers more categories than sex alone","Applies only to private employers","Was struck down by the Supreme Court"],1,
 "Texas adopted its own ERA covering sex, race, color, creed, and national origin, while the proposed federal ERA was never ratified."),
(16,"7","Analysis",
 "Texas v. Johnson (1989) established the principle that government may not:",
 ["Regulate the time, place, or manner of demonstrations","Prohibit expression simply because society finds the idea offensive","Require permits for parades","Punish true threats"],1,
 "The Court held that flag burning in political protest is protected expression, and that offensiveness alone is not a permissible basis for suppression."),

# ───────────────────────── Chapter 17 ─────────────────────────
(17,"8","Analysis",
 "The Texas electric grid operated by ERCOT is largely exempt from federal regulation because it:",
 ["Was granted a statutory exemption by Congress","Keeps electricity almost entirely within state lines, avoiding the interstate commerce that triggers FERC jurisdiction","Is owned by the state government","Produces only renewable energy"],1,
 "By avoiding significant interstate transfers, ERCOT remains largely outside Federal Energy Regulatory Commission jurisdiction. The trade-off is limited ability to import power during shortages."),
(17,"8","Application",
 "During Winter Storm Uri, the largest share of lost generation came from:",
 ["Wind turbines exclusively","Frozen equipment and natural gas supply failures affecting gas, coal, and nuclear plants as well as some wind","A cyberattack","Deliberate exports to other states"],1,
 "Although some wind generation iced, the majority of lost capacity was thermal, driven by frozen equipment and failures in the natural gas supply chain."),
(17,"8","Analysis",
 "Senate Bill 3 (2021) primarily responded to Winter Storm Uri by:",
 ["Connecting ERCOT to the national grids","Requiring weatherization of generators and critical natural gas facilities with inspections and penalties","Capping residential electricity rates permanently","Abolishing ERCOT"],1,
 "SB 3 mandated weatherization, improved emergency communication, and addressed the mapping of critical gas facilities so they would not lose power during load shedding."),
(17,"8","Application",
 "A landowner drills a well and pumps groundwater heavily, lowering a neighbor's water table. Under Texas law, this is generally permitted under:",
 ["Prior appropriation","The rule of capture","The public trust doctrine","Federal reserved water rights"],1,
 "The rule of capture generally allows landowners to pump groundwater beneath their property even if it affects neighbors, subject to any applicable groundwater conservation district rules."),
(17,"8","Comprehension",
 "Texas Proposition 4 (2025) dedicated funding for water infrastructure by:",
 ["Creating a new statewide water tax","Directing up to $1 billion a year of existing sales tax revenue to the Texas Water Fund for twenty years","Selling state parkland","Borrowing from the federal government"],1,
 "Proposition 4 dedicated existing sales tax revenue above a high threshold, creating no new tax, for two decades beginning in 2027."),

# ───────────────────────── Chapter 18 ─────────────────────────
(18,"4","Analysis",
 "The Texas Legislature passes a statute directing an agency to ensure facilities are 'safe and sanitary' and to adopt rules accordingly. This grant is best described as:",
 ["Judicial review","Delegated authority through enabling legislation","A line-item veto","An unfunded mandate"],1,
 "Enabling legislation creates an agency and delegates authority to fill in the details necessary to carry out a statute."),
(18,"4","Application",
 "A Texas agency's statutory Sunset date arrives and the Legislature takes no action. The agency is:",
 ["Continued automatically for 12 years","Abolished automatically","Transferred to the governor's office","Placed under federal supervision"],1,
 "The Sunset Act reverses the usual default: an agency is abolished on its Sunset date unless the Legislature affirmatively passes a bill continuing it."),
(18,"4","Comprehension",
 "An agency wishes to adopt a new binding rule. Before it takes effect, the agency must:",
 ["Obtain the governor's signature","Publish the proposed rule, allow public comment, and respond to significant comments","Win a two-thirds vote of the Senate","Receive approval from the Sunset Commission"],1,
 "The Administrative Procedure Act requires notice in the Texas Register, a comment period, and responses to significant comments before a rule becomes effective."),
(18,"4","Analysis",
 "Regulatory capture is best described as occurring when:",
 ["An agency is abolished through Sunset review","An agency comes to serve the interests of those it regulates rather than the public","The Legislature reduces an agency's budget","A court invalidates an agency rule"],1,
 "Capture typically arises through ordinary channels, including dependence on industry expertise, lopsided participation, and the revolving door, rather than through corruption."),
(18,"7","Application",
 "A Texan wants to obtain inspection reports held by a state agency. Under the Texas Public Information Act, the requester:",
 ["Must demonstrate a legal interest and explain the purpose of the request","May simply request the records, since the Act presumes openness and requires no stated reason","Must first file suit in district court","May obtain records only through a legislator"],1,
 "The Act establishes a strong presumption of openness; requesters need not justify their interest, and an agency seeking to withhold generally must obtain an Attorney General ruling."),
]
